### ISSUE TITLE
awk command is not working

### ISSUE THREAD

**Issue by Aneeqasif** [iris-cli/iris#3]
iris "Luna's Future lyrics" | awk '$1 == "GoogleLyrics" { $1=""; print substr($0,2) }'

is not prinitng any output , if i try iris only it give output ig theres some issue in bash command

**Comment by BeyondMagic** [comment]
Sorry about that, it's a bug that I have to fix and that isn't really that hard to modify on the source code as a workaround.

I was trying to implement an interactive mode so that in terminals the method are shown with colours. Unfortunately it is not working very well right now and you can remove it in the "Methods.hpp" file, the functions have "colour" in their names. Just take out the `033[..m` 
characters.

Or, easier, instead of `==` in the awk command, use `~`.

---

I will hopefully fix it soon.

**Comment by BeyondMagic** [comment]
Now you can use it normally :)
